### ISSUE TITLE
程序运行后，推流时提示无法连接

### ISSUE THREAD

**Issue by SnailTowardThesun** [simple-rtmp-server/go-srs#14]
使用go-srs，利用wiki里介绍的命令行推流，提示链接失败: Cannot open connection tcp://12.168.1.173:1935rtmp://12.168.1.173/live/livestream: Connection timed out
但是换成C++版本的srs的话，使用相同的命令行，是可以正常推流的。
另外，我没有办法kill掉 ./go-srs -c conf/srs.json进程，这个是为什么呢？

**Comment by winlinvip** [comment]
还没有支持推流呢，你可以看那个功能列表，在做基础功能哈，表捉急~
:smile:

**Comment by winlinvip** [comment]
https://github.com/simple-rtmp-server/go-srs#features

**Comment by SnailTowardThesun** [comment]
好的。。。话说。。怎么才能参加这个项目呢？

**Comment by winlinvip** [comment]
先把SRS的WIKI看一遍吧，这样知道go-srs要做什么（会比SRS多），然后你可以自己挑一个功能做。
https://github.com/simple-rtmp-server/srs/wiki/v2_CN_Home

**Comment by SnailTowardThesun** [comment]
好

**Comment by kuuyee** [comment]
go-oryx是一个完整的RTMP服务器吗？和SRS一样的东西？不依赖于SRS是吗？等于是SRS golang版实现，我可以这样理解吗？

**Comment by winlinvip** [comment]
下一代流媒体服务器，替代SRS的。
